### ISSUE TITLE
chore: install secret detection on pre-commit hooks

### ISSUE THREAD

**Issue by petermetz** [hyperledger-cacti/cacti#2290]
to catch secret before it leaves your machine and ease remediation.

### Description
As a developer, I want to incorporate a check so that any secrets/crypto doesn't get pushed to the github repo and this check runs as a part of pre-commit check

### Acceptance Criteria
1. Test should be done by incorporating various credentials/secrets like github secrets, aws secrets, pem files, access tokens

**Comment by zondervancalvez** [comment]
@jagpreetsinghsasan Please assign this to me. Thank you
