### ISSUE TITLE
ci(github): address Warning: The `save-state` command is deprecated

### ISSUE THREAD

**Issue by petermetz** [hyperledger-cacti/cacti#2361]
### Description

The `build-dev` job within `.github/workflows/ci.yml` generates the warning below. We need to address it:

```sh
Run actions/cache@v3.0.4
Warning: The `save-state` command is deprecated and will be disabled soon. 
Please upgrade to using Environment Files. For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### Acceptance Criteria
1. Warning is gone
2. Caching of the build files still works as intended

**Comment by Freedisch** [comment]
@petermetz Hello that seems like a good first issue for me, I could work on that if you don't mind

**Comment by petermetz** [comment]
@Freedisch Sorry for the very slow response! If you are still interested in solving this then we'd love to have a PR for it! Let me know!

**Comment by Freedisch** [comment]
> @Freedisch Sorry for the very slow response! If you are still interested in solving this then we'd love to have a PR for it! Let me know!

Got it, on it

**Comment by petermetz** [comment]
> > @Freedisch Sorry for the very slow response! If you are still interested in solving this then we'd love to have a PR for it! Let me know!
> 
> Got it, on it

@Freedisch Nice! FYI: If you get stuck with anything you can join the daily pair programming calls! More information can be found here: https://wiki.hyperledger.org/display/cactus/Daily+Pair+Programming+Calls

**Comment by aldousalvarez** [comment]
Hello @jagpreetsinghsasan, I would like to work on this one

**Comment by aldousalvarez** [comment]
@petermetz @jagpreetsinghsasan upon checking on one of our recent build-dev run on [main ](https://github.com/hyperledger-cacti/cacti/actions/runs/11394501409/job/31704942310) the warning on the `save-state command` is already gone

**Comment by petermetz** [comment]
@aldousalvarez Oh, great, thank you for confirming! I'm not sure when did we fix these, but great to know that it's done!
