### ISSUE TITLE
test(cmd-api-server): fix install-basic-plugin-ledger-connector-quorum-0-7-0

### ISSUE THREAD

**Issue by petermetz** [hyperledger-cacti/cacti#2545]
The test case that has to be skipped at the moment is this one:
`packages/cactus-cmd-api-server/src/test/typescript/unit/plugins/install-basic-plugin-ledger-connector-quorum-0-7-0.test.ts`

The goal of this task is to stop skipping the test by fixing it.

The fix is to have a published version of the quorum connector on npmjs.com
that isn't broken due to it not declaring its dependencies correctly.

So this issue is largely just waiting for the successful issuance of a new 
release and then re-enabling the test.

**Comment by solo-daemon** [comment]
Hi @jagpreetsinghsasan could you please assign me this issue?

**Comment by jagpreetsinghsasan** [comment]
Sure 🌻

**Comment by petermetz** [comment]
@solo-daemon @jagpreetsinghsasan FYI I think there's a PR in the review pipeline that refactors this test case so please be aware of that!
If I remember correctly I submitted the a pull request to deprecate the quorum connector plugin and I made this test case use Besu instead.

**Comment by petermetz** [comment]
The test has been refactored to verify the besu and fabric connector packages instead and those are now working fine. Closing this.
