### ISSUE TITLE
ci(release): add sigstore npm integration through --provenance

### ISSUE THREAD

**Issue by petermetz** [hyperledger-cacti/cacti#2623]
### Description
As a user of the Cacti npm packages I want to see on npmjs.com that the cacti packages are signed so that I have a layer of extra security against supply chain attacks that I can leverage.

https://github.blog/2023-04-19-introducing-npm-package-provenance/
https://blog.sigstore.dev/npm-public-beta/

### Acceptance Criteria
1. The complete list of cacti packages that we are publishing are published with the additional `--provenance` option so that the signature appears publicly on the registries ( for example https://www.npmjs.com/package/@hyperledger/cactus-cmd-api-server )
2. Release process is still fully automated (which is a work in progress task at the time of this writing but nevertheless...)
3. Any changes to the release process should be documented
4. We have to retain the ability to issue releases by multiple maintainers (so signing keys shouldn't be generated/distributed in a way that there's any single point of failure)

**Comment by adrianbatuto** [comment]
hi @jagpreetsinghsasan, I would like to work on this issue.
