### ISSUE TITLE
refactor(cmd-api-server): pull OAuth2 endpoint scopes from openapi.json

### ISSUE THREAD

**Issue by petermetz** [hyperledger-cacti/cacti#2693]
## Description 

1. Currently we do not specify the security section in the openapi.json files at all so this is the first thing to address 
2. Once the security sections in the spec files are consistent with the current implementation (JWTs with scopes for RBAC) then we can start refactoring the endpoint implementations in a way that uses the importer OpenAPI spec (the src/main/json/openapi.json files) security sections scope declarations instead of hardcoding it in the typescript code like it is done now)

## Acceptance Criteria 

1. Test coverage added to see that the scopes are indeed getting pulled from the spec file.

**Comment by aldousalvarez** [comment]
Hello @jagpreetsinghsasan I would like to work on this one, Thank you
