### ISSUE TITLE
build(codegen): fix cmd-api-server .jar download race condition - again

### ISSUE THREAD

**Issue by petermetz** [hyperledger-cacti/cacti#3015]
### Description

The .jar download mechanism and the warm-up script has gotten us far but now the cmd-api-server package's interfering with it. Most likely because that package declares the open api generator as a dev dependency on it's own and that is causing it to not use the same installation of the same package from the root node_modules and that's why it ends up re-downloading the .jar file. This is just a theory for now but an initial glance at the log file (attached below) seems to support this theory as does the fact that the past 3 times when I observed this crash on the CI it was always the cmd-api-server package causing the problem instead of it being randomly distributed among the packages like it was before.

[2024-02-07T15-54-14.0195638Z-cmd-api-server-codegen-race-condition.ci.test.crash.log](https://github.com/hyperledger/cacti/files/14196471/2024-02-07T15-54-14.0195638Z-cmd-api-server-codegen-race-condition.ci.test.crash.log)

Solution ideas:
1. Use the `--top-level` flag of the yarn CLI to force the usage of the root level node_modules directory's .jar file
2. Refactor the code so that the warm-up script copies the .jar file to all the locations where it's needed (e.g. all the package directories node_modules subfolders.)

### Acceptance Criteria
1. Race condition in the codegen script is eliminated.
3. No complicated logic has been introduced to fix it.

**Comment by ruzell22** [comment]
fixed by: #3289 and also tested 10 times while also limiting RAM to 7GB and vCPU cores to 2 and is running successfully.
