### ISSUE TITLE
chore(plugins): remove deprecated packages

### ISSUE THREAD

**Issue by outSH** [hyperledger-cacti/cacti#3155]
Deprecate and remove some older connectors and docker images as it was initially discussed during maintainer meetings https://wiki.hyperledger.org/display/cactus/2024-03-14+Cacti+Maintainers+Agenda and https://wiki.hyperledger.org/display/cactus/2024-03-20+Cacti+Maintainers+Agenda.

### The list of packages to be deprecated and removed

- ~`cacti-ledger-browser`~
    - We should rename `cacti-ledger-browser-react` as `cacti-ledger-browser`. I did not realize we've added a separate package in PR, sorry.
    - PR: https://github.com/hyperledger/cacti/pull/3170
- `cactus-cmd-socketio-server`
    - Deprecated by authors, should be moved to examples dir since it's still used by some sample apps. Removing it depends on some other connectors that are deprecated here.
- `cactus-plugin-ledger-connector-go-ethereum-socketio`
    - Replaced by `cactus-plugin-ledger-connector-ethereum`, should not be used anymore.
    - PR: https://github.com/hyperledger/cacti/pull/3341
- ~`cactus-plugin-ledger-connector-iroha`~
    - Not actively supported by the upstream, replaced with Iroha V2
    - PR https://github.com/hyperledger/cacti/pull/3160
    - Last commit: 4d2e5ce407652adcdeb6bab692bf119603e0dc28
- ~`docker/iroha-all-in-one`~
    - Not needed when connector is removed. We should also remove helper class from `cactus-test-tooling`.
    - PR https://github.com/hyperledger/cacti/pull/3160
    - Last commit: 4d2e5ce407652adcdeb6bab692bf119603e0dc28
- ~`docker/fabric-all-in-one V 1.4`~
    - Remove all-in-one image fabric V1, only V2 should be used from now on.
    - We should also remove helper class from `cactus-test-tooling` and upgrade any remaining tests and sample apps that use V1 (if any).
    - PR: https://github.com/hyperledger/cacti/pull/3299
    - Last commit: 4521d10e34c556434fe551f6d55100198b4d469d
- `cactus-plugin-ledger-connector-tcs-huawei-socketio`
    - All connectors in V2 should be openapi-based, refactor requested in https://github.com/hyperledger/cacti/issues/3076 and in https://github.com/hyperledger/cacti/issues/2820.
    - We'd love to re-add it once the refactor is done.
    - PR: https://github.com/hyperledger/cacti/pull/3342
- ~`cactus-example-tcs-huawei`~
    - Sample app uses deprecated `go-ethereum-socketio` and `tcs-huawei-socketio` connectors.
    - PR: https://github.com/hyperledger/cacti/pull/3158
    - Last commit: 36b8470f8a159bcb16c5ef62074aee2ff99758eb
- ~`cactus-plugin-ledger-connector-ubiquity`~
    - Package not supported and is breaking, removal already initiated by Rafael.
    - PR: https://github.com/hyperledger/cacti/pull/3142
    - Last commit: https://github.com/hyperledger/cacti/commit/ebea0f25b63ce5947b534d03a57d1b73a349a079
- TBD `cactus-plugin-ledger-connector-quorum`
    - Proposed by peter in https://github.com/hyperledger/cacti/issues/3026

### Deprecation and package removal is not final
If there's a need to bring some of these packages back, or if the package gets refactored so that it matches
the state of other cacti packages, then the package can be restored.  Removed packages can still be accessed by checking-out the state of this repo before the removal (I'll add appropriate commits next to the removed plugins on the list as the PR get merged).

### Motivation
We want to clean up older connectors before V2 release to simplify maitanance in the future. More packages means more dependencies that must be regularry checked and updated (security fixes), some of these packages are also deprecetad mainstream / by authors.

####  CC
@izuru0 @petermetz @takeutak @jagpreetsinghsasan @VRamakrishna @sandeepnRES @RafaelAPB @123wyl123

**Comment by petermetz** [comment]
@outSH Thank you for putting this together!

**Comment by RafaelAPB** [comment]
@outSH good initiative. Agree with all - I will do things on my end to remove the Ubiquity package (if/when we have support for this plugin within BD we can add it again)

**Comment by petermetz** [comment]
@outSH From what I can tell this has already been done: All the non-crossed out packages are actually missing from the codebase. Sounds like mission accomplished, thank you again! :-)

**Comment by RafaelAPB** [comment]
A bit late to the party, but thanks again for executing brilliantly this small behemoth of a task.
