### ISSUE TITLE
test(connector-besu): migrate get-block-endpoint test cases from Tap to Jest

### ISSUE THREAD

**Issue by krriscode** [hyperledger-cacti/cacti#3500]
Migrate all existing test cases for the get block endpoint to Jest

**Comment by krriscode** [comment]
Hi @petermetz,
requesting you to assign this issue, as we have discussed in one of the meet.

**Comment by petermetz** [comment]
@krriscode All yours! Thank you very much for the contributions in advance!

These are the test cases to be exact:

1. `packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-block-endpoint.test.ts`
2. `packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-block-endpoint.test.ts`
