### ISSUE TITLE
test(connector-besu): migrate get-past-logs test cases from Tap to Jest

### ISSUE THREAD

**Issue by Akshitha1020** [hyperledger-cacti/cacti#3505]
Migrate all existing test cases for the get past logs endpoint to Jest

**Comment by Akshitha1020** [comment]
Hi @petermetz,
requesting you to assign this issue, as we have discussed in one of the meet.

**Comment by petermetz** [comment]
@Akshitha1020 All yours, thank you very much for the contribution in advance! :-)
If you need any help feel free to join the pair programming calls that run each weekday!
