### ISSUE TITLE
test(connector-besu): jest migrate get-transaction-endpoint.test.ts

### ISSUE THREAD

**Issue by ArchanaArige** [hyperledger-cacti/cacti#3539]
https://github.com/hyperledger/cacti/blob/main/packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-transaction-endpoint.test.ts

**Comment by ArchanaArige** [comment]
hi @petermetz ,
Please assign this issue to me.

**Comment by petermetz** [comment]
@ArchanaArige All yours! Thank you in advance for the contributions, much appreciated! :-)
