### ISSUE TITLE
test(fabric): jestify test cases

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger-cacti/cacti#3547]
## Description
As a developer, I want to jestify the existing fabric connector test cases.
** For this, first make sure that the test which is being converted to use Jest, actually runs.

## Acceptance Criteria
1. Create a task to fix the failing tap test cases
2. Create a PR for the converted test cases (to Jest)

**Comment by petermetz** [comment]
@jagpreetsinghsasan Please make sure to include all the exact paths for the test cases that are being worked on as they are seen in the `.taprc` file.

Reason: I also randomly pick test cases to migrate from the `.taprc` file when I have some limited time to work on the smaller things and the way I make sure that there is no duplicate effort is that I do a search in the issue tracker with the path  of whatever test case I picked from `.taprc` and see if any hits come up and if yes, then I know someone else is working on that specific test case migration and I should not touch it. With this issue though, my search would come up as false negative and we would both work on it.

**Comment by jagpreetsinghsasan** [comment]
@petermetz we are covering all the test cases present, which can be moved to jest, so I havent pointed out the specific ones.
@adrianbatuto can you list down the test case names here, for reference?

**Comment by adrianbatuto** [comment]
These are the tests that are part of this ticket.

packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-javascript-source.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-typescript-source.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/openapi/openapi-validation-go.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/openapi/openapi-validation.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/unit/identity-internal-crypto-utils.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/obtain-profiles.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/identity-client.test.ts
