### ISSUE TITLE
docs(ledger-browser): add links to documentation

### ISSUE THREAD

**Issue by outSH** [hyperledger-cacti/cacti#3550]
**Is your feature request related to a problem? Please describe.**

Ledger browser apps have an option to provide links to relevant documentation pages. Since documentation for ledger-browser has been commited, we can link it in app definitions.

**Describe the solution you'd like**

Edit eth-browser and fabric-browser app configuration (e.g. https://github.com/hyperledger/cacti/blob/main/packages/cacti-ledger-browser/src/main/typescript/apps/eth/index.tsx) and set their `appDocumentationURL` and `appSetupGuideURL` to point to web docs (e.g. https://hyperledger.github.io/cacti/cactus/ledger-browser/plugin-apps/ethereum-browser/). Setup should point to Setup chapter.

See if links are displayed correctly when using the app (top-right corner) and creating and app (Setup guide link).

**Additional context**

For more info on app config see ledger-browser development guide (https://hyperledger.github.io/cacti/cactus/ledger-browser/developer-guide/overview/)

**Comment by sirisayshello** [comment]
Hi! I would like to work on this.

**Comment by outSH** [comment]
Great, thanks!
