### ISSUE TITLE
test(test-plugin-ledger-connector-besu): jestify v21-sign-transaction-endpoint

### ISSUE THREAD

**Issue by petermetz** [hyperledger-cacti/cacti#3565]
### Description

The task is to migrate a specific test case (relative path based below) to Jest from TAP:
`packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-sign-transaction-endpoint.test.ts`

An example pull request showing how these changes are to be done. Pay attention to the config file changes and the coding style of imports, describe() calls, it()/test() calls, the location of the variables storing the environment specific configuration that is created at runtime during the test execution, etc.

The example PR to use as a reference: https://github.com/hyperledger/cacti/pull/3206/files

### Acceptance Criteria
1. Test is only using Jest for assertions.
2. Config files updated (.taprc, ci.yaml, jest config, etc) so that the test has no hardcoded references to it in these files and instead gets picked up by the correct glob of the test job in ci.yaml related to the package housing the test.
3. Test is passing
4. The way the changes were done to the test case matches all the established patterns. See example PR linked above for the patterns of refactoring.

**Comment by suumona** [comment]
Hi @petermetz, I am working on this test file and currently its under internal evaluation

**Comment by petermetz** [comment]
@suumona This one seems taken, could you pick another one?
