### ISSUE TITLE
test(connector-besu): migrate v21-get-past-logs endpoint test cases from Tap to Jest

### ISSUE THREAD

**Issue by Udhayakumari** [hyperledger-cacti/cacti#3572]
Migrate all existing test cases for the v21 get past logs endpoint to Jest

[https://github.com/hyperledger/cacti/blob/main/packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/v21-get-past-logs-endpoint.test.ts](url)

**Comment by Udhayakumari** [comment]
Hi @petermetz , 
Please assign this issue to me.

**Comment by petermetz** [comment]
@Udhayakumari Done, thank you very much for the contributions in advance! If you need any help just dial in to the pair programming session that's running on weekdays at 10 AM Pacific Time
