### ISSUE TITLE
test(htlc-eth-besu-erc20): migrate get-status-endpoint test cases from Tape to Jest

### ISSUE THREAD

**Issue by Udhayakumari** [hyperledger-cacti/cacti#3650]
Need to migrate all existing test cases for the get-status-endpoint to Jest

[https://github.com/hyperledger-cacti/cacti/blob/main/packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts](url)

**Comment by Udhayakumari** [comment]
Hi @petermetz, please assign this issue to me!

**Comment by petermetz** [comment]
@Udhayakumari Sorry for the slow response! 
@outSH Thank you for stepping in!
