### ISSUE TITLE
ci(trivy): fix scan failures due to TOOMANYREQUESTS DB error

### ISSUE THREAD

**Issue by aldousalvarez** [hyperledger-cacti/cacti#3652]
### Description

The Trivy scan in our GitHub Actions workflow is producing inconsistent results and often fails to scan. The most frequent issue is a database download error caused by rate limits (TOOMANYREQUESTS: retry-after). This prevents Trivy from completing the scan, resulting in a DB error.

Error logs can be seen here: [https://github.com/hyperledger-cacti/cacti/actions/runs/12025612225/job/33524333591?pr=3622](url)

[cmd-api-server-trivy scan logs.txt](https://github.com/user-attachments/files/17916669/cmd-api-server-trivy.scan.logs.txt)

### **Steps to reproduce:**

1. Run the Trivy scan using the aquasecurity/trivy-action@0.19.0 action.
2. Observe the frequent failure during the database download step.

### Expected behavior: 
1. Trivy should consistently complete the scan without errors.

**Comment by petermetz** [comment]
Idea: transition the trivy scans to a weekly scan so that we don't have to  deal with the rate limits for now.
